dataset:
  name: breast_mnist
  data_root: ./data
  batch_size: 32
  num_workers: 2
  download: true
  color_space: GRAYSCALE
model:
  architecture: original
  num_classes: 2
  kernel_size: 3
  stride: 3
  kernel_topology_names:
  - vertical
  scaling_factor: 1.0
  evolution_time: 2.5
  mode: trotter
  encoding_mode: digital
  include_correlators: true
  dropout: 0.5663561524251373
  activation: relu
  quantum_device: default.qubit
  classical_device: auto
optim:
  lr: 0.0012800666165098302
  weight_decay: 0.0001018708824762185
  epochs: 100
  grad_clip: 7.831182940640814
  patience: 71
  use_scheduler: true
  scheduler_T_max: 100
  scheduler_eta_min: 0.0
misc:
  seed:
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  log_every: 50