dataset:
    name: breast_mnist_64
    data_root: ./data
    batch_size: 32
    num_workers: 2
    download: true
    color_space: GRAYSCALE

model:
    num_classes: 2
    kernel_size: 4
    stride: 4
    kernel_topology_names:
        - kings
        - horizontal_chains
        - vertical_chains
        - diagonal_chains
        - block_2x2
    scaling_factor: 1.0
    evolution_time: 1.0
    mode: trotter
    dropout: 0.6
    activation: gelu # relu or gelu
    quantum_device: default.qubit
    quantum_device_kwargs: {}
    classical_device: auto # auto, cuda, or cpu - auto detects GPU availability

optim:
    lr: 0.0001
    weight_decay: 1e-7
    epochs: 100
    grad_clip: 1.0
    patience: 1000
    use_scheduler: true
    scheduler_T_max: 100
    scheduler_eta_min: 0.0

misc:
    seed: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    log_every: 50
