dataset:
  name: breast_mnist
  data_root: ./data
  batch_size: 32
  num_workers: 2
  download: true

model:
  num_classes: 2
  kernel_size: 2
  stride: 1
  kernel_topology_names: ["kings", "horizontal", "vertical", "square"]
  scaling_factor: 1.0
  evolution_time: 0.2
  mode: trotter
  dropout: 0.6
  activation: gelu # relu or gelu
  quantum_device: default.qubit
  quantum_device_kwargs: {}
  classical_device: auto # auto, cuda, or cpu - auto detects GPU availability

optim:
  lr: 3e-4
  weight_decay: 1e-06
  epochs: 10
  grad_clip: 1.0
  patience: 5

misc:
  seed: 0
  log_every: 50
