"""
Oracle-Routed Mixture-of-Topologies: Image-Level Router.

A lightweight CNN that predicts, from a raw input image, which quantum kernel
topology will perform best for that sample.  At inference time only the
predicted topology's quantum kernel is evaluated, giving multi-kernel accuracy
at single-kernel computational cost.

The router is trained on *oracle labels* generated by per-topology classifiers
(Phase 1), not by a Teacher attention mechanism.
"""

import torch
import torch.nn as nn


class OracleRouter(nn.Module):
    """Lightweight image-level topology router.

    Architecture:
        Conv2d → BN → Act → Pool → Conv2d → BN → Act → Pool
        → Flatten → Linear → Dropout → Linear(num_topologies)

    The default architecture is deliberately small (<20k params for 28x28
    grayscale input) because the routing task is coarse (M-way classification
    where M is typically 4-8).

    Args:
        in_channels: Number of input image channels (1 for grayscale, 3 for RGB).
        num_topologies: Number of topology classes to route among.
        hidden_dims: List of hidden dimensions for the convolutional blocks.
            Default [16, 32] gives a small but effective feature extractor.
        fc_dim: Hidden dimension of the FC layer before the output logits.
        dropout: Dropout rate applied in the FC layers.
    """

    def __init__(
        self,
        in_channels: int = 1,
        num_topologies: int = 4,
        hidden_dims: list | None = None,
        fc_dim: int = 64,
        dropout: float = 0.3,
    ):
        super().__init__()
        if hidden_dims is None:
            hidden_dims = [16, 32]

        self.num_topologies = num_topologies

        # Build convolutional feature extractor
        layers = []
        ch_in = in_channels
        for ch_out in hidden_dims:
            layers.extend([
                nn.Conv2d(ch_in, ch_out, kernel_size=3, padding=1),
                nn.BatchNorm2d(ch_out),
                nn.ReLU(inplace=True),
                nn.MaxPool2d(2),
            ])
            ch_in = ch_out
        self.features = nn.Sequential(*layers)

        # Classifier head (uses LazyLinear to infer flattened size)
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.LazyLinear(fc_dim),
            nn.ReLU(inplace=True),
            nn.Dropout(dropout),
            nn.Linear(fc_dim, num_topologies),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Forward pass.

        Args:
            x: (B, C, H, W) raw image tensor.

        Returns:
            (B, num_topologies) logits.
        """
        h = self.features(x)
        return self.classifier(h)

    def predict_topology(self, x: torch.Tensor) -> torch.Tensor:
        """Predict the best topology index per image.

        Args:
            x: (B, C, H, W) raw image tensor.

        Returns:
            (B,) LongTensor of topology indices.
        """
        logits = self.forward(x)
        return logits.argmax(dim=1)
